name: Verify

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Verify
    uses: takari/takari-gh-actions/.github/workflows/ci.yml@v3
    with:
      jdk-matrix: '[ 11,17,21 ]'
